# Site settings
title: Diego Gonzalez
description: Curriculum Online
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Diego Gonz치lez
user_description: Ingeniero Inform치tico por la Universidad de Burgos. Estudiante del master de Seguridad Ofensiva. Preparandome para la certificacion OSCP.
user_title: Computer Engineer
email: diegonzalez_96@hotmail.com
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
linkedin_username: diego-gonz치lez-rom치n-344b40140
github_username:  diegonzalezro
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
